services:
  jaeger:
    image: jaegertracing/all-in-one:1.44
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  telemetry:
    image: otel/opentelemetry-collector:0.76.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ${PWD}/docker/telemetry.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger

  test-app:
    image: node:18.17.1-buster-slim
    working_dir: /app
    volumes:
      - .:/app
      - ${PWD}/test-app:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm run dev"
    depends_on:
      - telemetry
